// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeGGTWEqH2nOtCnVHSChK_ZwUNY2z_oY0',
    appId: '1:451335787178:web:9fd8ee688ca160cb0eb6d3',
    messagingSenderId: '451335787178',
    projectId: 'crudtodowithauth',
    authDomain: 'crudtodowithauth.firebaseapp.com',
    storageBucket: 'crudtodowithauth.appspot.com',
    measurementId: 'G-CN373DCBW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxYAVxNSJWXlPZ1oZLHtYbp0Y-q3frH8',
    appId: '1:451335787178:android:d525ff69c66cc1b60eb6d3',
    messagingSenderId: '451335787178',
    projectId: 'crudtodowithauth',
    storageBucket: 'crudtodowithauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzNnt37OqwQYQJnCIEd873bk_ufmx-DOU',
    appId: '1:451335787178:ios:ab755a03e6ae18ec0eb6d3',
    messagingSenderId: '451335787178',
    projectId: 'crudtodowithauth',
    storageBucket: 'crudtodowithauth.appspot.com',
    iosClientId: '451335787178-8jj13gsid3ps0r021po74vum4dla441o.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzNnt37OqwQYQJnCIEd873bk_ufmx-DOU',
    appId: '1:451335787178:ios:4cd1b3da480a1bc40eb6d3',
    messagingSenderId: '451335787178',
    projectId: 'crudtodowithauth',
    storageBucket: 'crudtodowithauth.appspot.com',
    iosClientId: '451335787178-b289t2cmav9mpi38k68vf2ehhl604lhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppWithFirebase.RunnerTests',
  );
}
